USE Softblue2;

SHOW ENGINES;

CREATE TABLE CONTA_BANCARIA
(
ID INTEGER UNSIGNED NOT NULL AUTO_INCREMENT, -- Código interno (PK)
titular VARCHAR(32) NOT NULL, -- Nome do titular da conta
saldo DOUBLE NOT NULL, -- Representa o saldo da conta
PRIMARY KEY(ID) -- Define o campo CODIGO como PK (Primary Key)
) engine = InnoDB;

INSERT INTO CONTA_BANCARIA VALUES (1, 'André', 213);
INSERT INTO CONTA_BANCARIA VALUES (2, 'Diogo', 489);
INSERT INTO CONTA_BANCARIA VALUES (3, 'Rafael', 568);
INSERT INTO CONTA_BANCARIA VALUES (4, 'Carlos', 712);
INSERT INTO CONTA_BANCARIA VALUES (5, 'Peter', -38);

SELECT * FROM CONTA_BANCARIA;

START TRANSACTION;
UPDATE CONTA_BANCARIA SET saldo = saldo - 100 WHERE id = 1;
UPDATE CONTA_BANCARIA SET saldo = saldo + 100 WHERE id = 2;
ROLLBACK;

START TRANSACTION;
UPDATE CONTA_BANCARIA SET saldo = saldo*1.04 WHERE saldo > 0;
commit;